### ISSUE TITLE
Did you check documentation? What is behavior if there is no subscriptions? Will it return empty list or null?

### ISSUE THREAD

**Issue by Nemf1s** [kshissh/spring#9]
https://github.com/kshissh/spring/blob/f8c8371edd73b86c4db85df3982576800f66556d/SpringBoot/NotificationDispatcher/src/main/java/com/example/notificationdispatcher/SubscriptionRepository.java#L18

**Comment by kshissh** [comment]
No, I didn't. But in my experience using that method, I noticed that it usually returns an empty list
